workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        # Define your environment variables here
    scripts:
      - name: Install dependencies
        script: |
          # Your commands to install dependencies
      - name: Run tests
        script: |
          # Your commands to run tests
      - name: Build and package
        script: |
          # Your commands to build and package your app
    artifacts:
      - build/**.apk
      - build/**.ipa
